export enum COUNTRIES {
  FRANCE = 'France',
  CROATIA = 'Croatia',
  WEST_GERMANY = 'West Germany',
  ARGENTINA = 'Argentina',
  BRAZIL = 'Brazil',
  ITALY = 'Italy',
  GERMANY = 'Germany',
  NETHERLANDS = 'Netherlands',
  SPAIN = 'Spain',
  ENGLAND = 'England',
  SWEDEN = 'Sweden',
  CZECHOSLOVAKIA = 'Czechoslovakia',
  URUGUAY = 'Uruguay',
  HUNGARY = 'Hungary',
}
